name: Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          ./Pilot_Episode/fetch_dependencies.py Pilot_Episode/dependencies -y
      
      # Step 3: Change to the correct directory and build
      - name: Build project
        run: |
          cd Pilot_Episode/Pilot_Episode
          ./build.sh
